[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

; Enable 8MB OPI PSRAM & OTA Partitions for Multi-Level Memory Manager & USB App Store
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_8MB.csv
build_flags = -DBOARD_HAS_PSRAM

; Lock programming & hardware monitor to COM7
upload_port = COM7
monitor_port = COM7


monitor_speed = 115200
monitor_filters = esp32_exception_decoder, default, time

lib_deps = 
    firechip/usb-host-msc
